added issue and pull request templates
nss-evening-cohort-14/gitsub-e14-team-2-electric-boogaloo pull request #14
Opened 2021-02-06 18:23 UTC by GonzalesMatthew

- added PULL_REQUEST_TEMPLATE.md
- added ISSUE_TICKET.md

2021-02-06 18:30 UTC, HunterJuneau commented
Want to go ahead and add index.html, main.js, and main.css?

2021-02-06 18:30 UTC, HunterJuneau requested changes
Need the HTML, CSS, and JS files.

2021-02-09 00:18 UTC, hmparsons-sde approved these changes

2021-02-09 00:18 UTC, seancrossettie approved these changes

2021-02-09 00:18 UTC, HunterJuneau approved these changes

2021-02-09 00:18 UTC, merged