Began Organizations page
nss-evening-cohort-14/gitsub-e14-team-2-electric-boogaloo pull request #51
Opened 2021-02-10 02:47 UTC by GonzalesMatthew

## Description
- Created organizations.html
- connected between index.html and organizationas.html via nav links
- created organizations data object
- looped through object to print to Org page DOM
- 
## Related Issue
#47 

## Motivation and Context
Required for MVP

## How Can This Be Tested?
Pull repo, navigate to Organizations page and see that organizations cards exist

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-02-10 02:54 UTC, Gabrielle-Tobermann approved these changes

2021-02-10 03:28 UTC, HunterJuneau requested changes
Getting the following error on the home page: 
```
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at printToDom (main.js:37)
    at createCards (main.js:47)
    at init (main.js:124)
    at main.js:127
```

2021-02-10 21:26 UTC, seancrossettie requested changes
Resolve your conflicts. After that it should be good to push to Development.

2021-02-12 00:29 UTC, hmparsons-sde approved these changes

2021-02-12 00:51 UTC, HunterJuneau approved these changes

2021-02-12 00:52 UTC, seancrossettie approved these changes

2021-02-12 00:53 UTC, merged