added search bar and extra styling
nss-evening-cohort-14/gitsub-e14-team-2-electric-boogaloo pull request #81
Opened 2021-02-14 21:15 UTC by seancrossettie

Added Search Bar

## Description
Added a search bar for Packages. 

## Related Issue
https://github.com/nss-evening-cohort-14/gitsub-e14-team-2-electric-boogaloo/issues/37

## Motivation and Context
Packages Page Stretch

## How Can This Be Tested?
``` 
git fetch origin sr-search-packages
sudo hs -o
```
## Screenshots (if appropriate):
<img width="1657" alt="Screen Shot 2021-02-14 at 3 15 12 PM" src="https://user-images.githubusercontent.com/76828201/107889341-70894380-6ed7-11eb-98c4-a27d763e8c45.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-02-14 22:50 UTC, hmparsons-sde approved these changes

2021-02-15 03:29 UTC, Gabrielle-Tobermann reviewed
It looks really good! Only thing is, on my server your cards show up under the profile no matter how big the screen is.

2021-02-15 19:51 UTC, HunterJuneau requested changes
- I think it would be better if the search bar was above the packages.
- The search bar wasn't working for me. It isn't doing anything and there aren't any errors.

2021-02-15 20:14 UTC, GonzalesMatthew requested changes
Search bar isn't working
- also is it searching for title words? description words? not sure what to enter into search bar.

2021-02-15 21:10 UTC, HunterJuneau approved these changes

2021-02-15 21:13 UTC, hmparsons-sde approved these changes

2021-02-15 21:30 UTC, closed without merging